import type { ThreatActor, Campaign, Vulnerability, IOC, ThreatFeed } from "@/types";

export const mockThreatActors: ThreatActor[] = [
  {
    id: "apt28",
    name: "APT28",
    aliases: ["Fancy Bear", "Sofacy", "Pawn Storm", "STRONTIUM"],
    type: "apt",
    motivation: "State-sponsored intelligence gathering",
    origin: "Russia",
    targetSectors: ["Government", "Military", "Energy", "Aerospace", "Media"],
    targetCountries: ["USA", "UK", "Germany", "France", "Ukraine", "Georgia"],
    capabilities: ["Zero-day exploits", "Spear-phishing", "Credential harvesting", "Supply chain attacks"],
    tools: ["X-Agent", "X-Tunnel", "Zebrocy", "Koadic", "Mimikatz"],
    malware: ["Sofacy", "X-Agent", "Zebrocy", "CompuTrace"],
    campaigns: ["Operation Pawn Storm", "Election interference", "Olympic Destroyer"],
    ttps: ["T1566", "T1059", "T1053", "T1071", "T1090", "T1574"],
    confidence: 95,
    active: true,
    lastActivity: new Date("2026-06-20"),
    description: "Russian military intelligence (GRU) cyber espionage group known for targeting government and military organizations worldwide."
  },
  {
    id: "apt29",
    name: "APT29",
    aliases: ["Cozy Bear", "The Dukes", "NOBELIUM"],
    type: "apt",
    motivation: "State-sponsored intelligence gathering",
    origin: "Russia",
    targetSectors: ["Government", "Technology", "Healthcare", "Think Tanks"],
    targetCountries: ["USA", "UK", "Netherlands", "Germany"],
    capabilities: ["Supply chain compromise", "Cloud infrastructure attacks", "Zero-day exploitation"],
    tools: ["WellMess", "WellMail", "Sunburst", "SUNSHUTTLE"],
    malware: ["WellMess", "WellMail", "Sunburst", "EnvyScout"],
    campaigns: ["SolarWinds Supply Chain Attack", "COVID-19 Research Targeting"],
    ttps: ["T1195", "T1133", "T1557", "T1021", "T1078"],
    confidence: 93,
    active: true,
    lastActivity: new Date("2026-06-18"),
    description: "Russian SVR cyber espionage group known for sophisticated supply chain attacks."
  },
  {
    id: "lazarus",
    name: "Lazarus Group",
    aliases: ["HIDDEN COBRA", "Zinc", "Labyrinth Chollima"],
    type: "apt",
    motivation: "Financial gain + Espionage",
    origin: "North Korea",
    targetSectors: ["Financial", "Cryptocurrency", "Technology", "Manufacturing"],
    targetCountries: ["USA", "Japan", "South Korea", "India", "UK"],
    capabilities: ["Custom malware", "Social engineering", "Cryptocurrency theft", "Supply chain attacks"],
    tools: ["FALLCHILL", "HOPLIGHT", "AppleJeus", "TraderTraitor"],
    malware: ["FALLCHILL", "HOPLIGHT", "Manuscrypt", "VHD"],
    campaigns: ["AppleJeus", "Operation Dream Job", "SWIFT Banking Attacks"],
    ttps: ["T1566", "T1204", "T1059", "T1027", "T1105"],
    confidence: 92,
    active: true,
    lastActivity: new Date("2026-06-22"),
    description: "North Korean state-sponsored group known for both espionage and financially motivated attacks."
  },
  {
    id: "lockbit",
    name: "LockBit",
    aliases: ["LockBit 3.0", "LockBit Black"],
    type: "ransomware",
    motivation: "Financial gain",
    origin: "Russia",
    targetSectors: ["Manufacturing", "Healthcare", "Government", "Education", "Technology"],
    targetCountries: ["USA", "UK", "Germany", "France", "Italy", "Canada"],
    capabilities: ["Ransomware-as-a-Service", "Double extortion", "Data exfiltration", "Active Directory exploitation"],
    tools: ["Cobalt Strike", "Mimikatz", "PsExec", "Rclone"],
    malware: ["LockBit 3.0", "LockBit Black"],
    campaigns: ["LockBit 3.0 RaaS Operations"],
    ttps: ["T1486", "T1490", "T1489", "T1027", "T1562"],
    confidence: 90,
    active: true,
    lastActivity: new Date("2026-06-25"),
    description: "Prominent ransomware-as-a-service operation with global reach."
  },
  {
    id: "chameleon",
    name: "Chameleon",
    aliases: ["Chameleon malware"],
    type: "cybercriminal",
    motivation: "Financial gain",
    origin: "Unknown",
    targetSectors: ["Banking", "Cryptocurrency", "E-commerce"],
    targetCountries: ["Global"],
    capabilities: ["Adware", "Credential theft", "Browser manipulation"],
    tools: ["Chameleon", "Raccoon Stealer"],
    malware: ["Chameleon"],
    campaigns: ["Banking Trojan Campaigns"],
    ttps: ["T1555", "T1539", "T1185", "T1056"],
    confidence: 75,
    active: true,
    lastActivity: new Date("2026-06-21"),
    description: "Emerging banking trojan with advanced evasion capabilities."
  },
  {
    id: "salt-typhoon",
    name: "Salt Typhoon",
    aliases: ["Ghost Emperor", "Famous Sparrow"],
    type: "apt",
    motivation: "State-sponsored intelligence gathering",
    origin: "China",
    targetSectors: ["Telecommunications", "Government", "Technology"],
    targetCountries: ["USA", "UK", "France", "India"],
    capabilities: ["Network exploitation", "Long-term persistence", "Living-off-the-land"],
    tools: ["WebShell", "Cobalt Strike", "Mimikatz"],
    malware: ["Coathanger", "Dreambus"],
    campaigns: ["Telecommunications Infiltration"],
    ttps: ["T1190", "T1078", "T1053", "T1547"],
    confidence: 85,
    active: true,
    lastActivity: new Date("2026-06-19"),
    description: "Chinese state-sponsored group targeting telecommunications infrastructure."
  }
];

export const mockCampaigns: Campaign[] = [
  {
    id: "camp-001",
    name: "Operation Shadow Network",
    threatActor: "APT28",
    status: "active",
    startDate: new Date("2026-03-15"),
    targetSectors: ["Government", "Defense"],
    targetCountries: ["USA", "UK", "Germany"],
    malware: ["X-Agent", "Zebrocy"],
    ttps: ["T1566", "T1059", "T1053"],
    iocs: ["185.220.101.x", "malicious-domain.com"],
    description: "Large-scale espionage campaign targeting NATO-aligned governments.",
    confidence: 88,
  },
  {
    id: "camp-002",
    name: "CryptoHeist 2026",
    threatActor: "Lazarus Group",
    status: "active",
    startDate: new Date("2026-05-01"),
    targetSectors: ["Cryptocurrency", "DeFi"],
    targetCountries: ["Japan", "South Korea", "Singapore"],
    malware: ["AppleJeus", "FALLCHILL"],
    ttps: ["T1566", "T1204", "T1059"],
    iocs: ["fake-exchange.com", "0x1234...abcd"],
    description: "Ongoing campaign targeting cryptocurrency exchanges and DeFi protocols.",
    confidence: 85,
  },
  {
    id: "camp-003",
    name: "Healthcare Breach Wave",
    threatActor: "LockBit",
    status: "active",
    startDate: new Date("2026-06-01"),
    targetSectors: ["Healthcare", "Pharmaceutical"],
    targetCountries: ["USA", "Canada", "UK"],
    malware: ["LockBit 3.0"],
    ttps: ["T1486", "T1490", "T1027"],
    iocs: ["healthcare-leak.onion"],
    description: "Ransomware campaign specifically targeting healthcare infrastructure.",
    confidence: 82,
  },
  {
    id: "camp-004",
    name: "TelecomSpy",
    threatActor: "Salt Typhoon",
    status: "active",
    startDate: new Date("2026-01-10"),
    targetSectors: ["Telecommunications"],
    targetCountries: ["USA", "UK", "India"],
    malware: ["Coathanger"],
    ttps: ["T1190", "T1078", "T1547"],
    iocs: ["compromised-router-config"],
    description: "Long-term intelligence operation against major telecom providers.",
    confidence: 80,
  }
];

export const mockVulnerabilities: Vulnerability[] = [
  {
    id: "vuln-001",
    cve: "CVE-2026-3821",
    cvss: 9.8,
    epss: 0.94,
    kev: true,
    exploited: true,
    description: "Critical RCE in Fortinet FortiOS SSL-VPN allowing unauthenticated remote code execution.",
    affectedSoftware: ["FortiOS 7.x", "FortiOS 6.x"],
    malware: ["LockBit 3.0", "APT28 tools"],
    apt: ["APT28", "APT29"],
    mitigation: "Apply vendor patch immediately. If unable to patch, disable SSL-VPN.",
    publishedDate: new Date("2026-06-15"),
  },
  {
    id: "vuln-002",
    cve: "CVE-2026-21887",
    cvss: 9.1,
    epss: 0.87,
    kev: true,
    exploited: true,
    description: "Command injection vulnerability in VMware vCenter Server.",
    affectedSoftware: ["VMware vCenter Server 8.x", "VMware vCenter Server 7.x"],
    malware: ["Ransomware variants"],
    apt: ["Lazarus Group"],
    mitigation: "Apply vendor patches. Restrict network access to vCenter.",
    publishedDate: new Date("2026-06-10"),
  },
  {
    id: "vuln-003",
    cve: "CVE-2026-46884",
    cvss: 8.8,
    epss: 0.72,
    kev: false,
    exploited: false,
    description: "Privilege escalation in Microsoft Windows Print Spooler.",
    affectedSoftware: ["Windows Server 2022", "Windows 11"],
    malware: ["Various post-exploitation tools"],
    apt: ["Multiple APT groups"],
    mitigation: "Apply Microsoft security update. Disable Print Spooler if not needed.",
    publishedDate: new Date("2026-06-20"),
  },
  {
    id: "vuln-004",
    cve: "CVE-2026-55432",
    cvss: 9.4,
    epss: 0.91,
    kev: true,
    exploited: true,
    description: "Critical authentication bypass in Cisco IOS XE.",
    affectedSoftware: ["Cisco IOS XE 17.x", "Cisco IOS XE 16.x"],
    malware: ["Salt Typhoon tools"],
    apt: ["Salt Typhoon"],
    mitigation: "Apply patch immediately. Implement ACLs.",
    publishedDate: new Date("2026-06-18"),
  },
];

export const mockIOCs: IOC[] = [
  {
    id: "ioc-001",
    type: "ip",
    value: "185.220.101.45",
    threatLevel: "critical",
    confidence: 95,
    reputation: 0,
    firstSeen: new Date("2026-05-01"),
    lastSeen: new Date("2026-06-25"),
    source: "BlackSentinel Pulse",
    tags: ["APT28", "C2", "Espionage"],
    campaigns: ["Operation Shadow Network"],
    malware: ["X-Agent", "Zebrocy"],
    apt: ["APT28"],
    mitreTactics: ["T1071", "T1573"],
    geolocation: "Russia",
    context: "Command and control server for X-Agent implant."
  },
  {
    id: "ioc-002",
    type: "domain",
    value: "crypto-exchange-update.com",
    threatLevel: "high",
    confidence: 88,
    reputation: 10,
    firstSeen: new Date("2026-06-01"),
    lastSeen: new Date("2026-06-24"),
    source: "OSINT Feed",
    tags: ["Lazarus", "Phishing", "Cryptocurrency"],
    campaigns: ["CryptoHeist 2026"],
    malware: ["AppleJeus"],
    apt: ["Lazarus Group"],
    mitreTactics: ["T1566", "T1105"],
    context: "Phishing domain impersonating cryptocurrency exchange."
  },
  {
    id: "ioc-003",
    type: "hash",
    value: "a1b2c3d4e5f6789012345678901234567890abcd",
    threatLevel: "critical",
    confidence: 92,
    reputation: 0,
    firstSeen: new Date("2026-06-10"),
    lastSeen: new Date("2026-06-25"),
    source: "VirusTotal",
    tags: ["LockBit 3.0", "Ransomware", "Payload"],
    campaigns: ["Healthcare Breach Wave"],
    malware: ["LockBit 3.0"],
    apt: ["LockBit"],
    mitreTactics: ["T1486", "T1027"],
    context: "LockBit 3.0 ransomware payload detected in healthcare attacks."
  },
  {
    id: "ioc-004",
    type: "domain",
    value: "microsoft-update-cdn.net",
    threatLevel: "high",
    confidence: 85,
    reputation: 5,
    firstSeen: new Date("2026-06-15"),
    lastSeen: new Date("2026-06-23"),
    source: "Dark Web Intelligence",
    tags: ["Typosquatting", "Phishing", "Credential Theft"],
    campaigns: ["Credential Harvesting"],
    malware: ["Chameleon"],
    apt: [],
    mitreTactics: ["T1566", "T1539"],
    context: "Typosquatting domain used for credential harvesting."
  },
];

export const mockFeeds: ThreatFeed[] = [
  { id: "feed-001", name: "AlienVault OTX", type: "osint", status: "active", lastUpdate: new Date("2026-06-25T10:30:00"), iocCount: 2847392, confidence: 75, reliability: "C" },
  { id: "feed-002", name: "Abuse.ch URLhaus", type: "osint", status: "active", lastUpdate: new Date("2026-06-25T10:28:00"), iocCount: 892341, confidence: 85, reliability: "B" },
  { id: "feed-003", name: "CISA KEV", type: "government", status: "active", lastUpdate: new Date("2026-06-25T06:00:00"), iocCount: 1247, confidence: 98, reliability: "A" },
  { id: "feed-004", name: "VirusTotal Live Hunt", type: "commercial", status: "active", lastUpdate: new Date("2026-06-25T10:25:00"), iocCount: 5678234, confidence: 90, reliability: "A" },
  { id: "feed-005", name: "BlackSentinel Pulse", type: "osint", status: "active", lastUpdate: new Date("2026-06-25T10:32:00"), iocCount: 1245678, confidence: 95, reliability: "A" },
  { id: "feed-006", name: "DarkOwl Vision", type: "darkweb", status: "active", lastUpdate: new Date("2026-06-25T09:00:00"), iocCount: 345678, confidence: 80, reliability: "B" },
  { id: "feed-007", name: "Recorded Future", type: "commercial", status: "active", lastUpdate: new Date("2026-06-25T10:20:00"), iocCount: 8901234, confidence: 92, reliability: "A" },
  { id: "feed-008", name: "MITRE ATT&CK", type: "government", status: "active", lastUpdate: new Date("2026-06-24T12:00:00"), iocCount: 0, confidence: 100, reliability: "A" },
];

export const mockAlerts = [
  { id: "alert-001", title: "APT28 C2 Server Detected in Network Range", severity: "critical" as const, source: "BlackSentinel Guardian", timestamp: new Date("2026-06-25T10:15:00"), read: false, category: "Threat Detection", relatedAssets: ["192.168.1.0/24"] },
  { id: "alert-002", title: "New CVE-2026-3821 Exploit Attempts Detected", severity: "critical" as const, source: "BlackSentinel Pulse", timestamp: new Date("2026-06-25T09:45:00"), read: false, category: "Vulnerability", relatedAssets: ["FortiGate-60F", "FortiGate-100F"] },
  { id: "alert-003", title: "LockBit 3.0 Ransomware Hash Detected", severity: "high" as const, source: "BlackSentinel Nexus", timestamp: new Date("2026-06-25T08:30:00"), read: false, category: "Malware", relatedAssets: ["WS-DEPT-045"] },
  { id: "alert-004", title: "Typosquatting Domain Registered for Brand", severity: "medium" as const, source: "Digital Risk Protection", timestamp: new Date("2026-06-25T07:00:00"), read: true, category: "Brand Protection", relatedAssets: ["blacksentinel.com"] },
  { id: "alert-005", title: "Credential Leak Detected on Dark Web Forum", severity: "high" as const, source: "Dark Web Intelligence", timestamp: new Date("2026-06-24T22:00:00"), read: true, category: "Dark Web", relatedAssets: ["corporate-credentials"] },
];

export const mitreData = {
  tactics: [
    { id: "TA0043", name: "Reconnaissance", techniques: ["T1595", "T1592", "T1589", "T1598"] },
    { id: "TA0042", name: "Resource Development", techniques: ["T1583", "T1584", "T1587", "T1588"] },
    { id: "TA0001", name: "Initial Access", techniques: ["T1189", "T1190", "T1133", "T1566"] },
    { id: "TA0002", name: "Execution", techniques: ["T1059", "T1203", "T1047", "T1053"] },
    { id: "TA0003", name: "Persistence", techniques: ["T1547", "T1136", "T1505", "T1574"] },
    { id: "TA0004", name: "Privilege Escalation", techniques: ["T1068", "T1055", "T1548", "T1134"] },
    { id: "TA0005", name: "Defense Evasion", techniques: ["T1027", "T1070", "T1036", "T1562"] },
    { id: "TA0006", name: "Credential Access", techniques: ["T1003", "T1110", "T1555", "T1539"] },
    { id: "TA0007", name: "Discovery", techniques: ["T1046", "T1082", "T1083", "T1018"] },
    { id: "TA0008", name: "Lateral Movement", techniques: ["T1021", "T1570", "T1550"] },
    { id: "TA0009", name: "Collection", techniques: ["T1005", "T1039", "T1560"] },
    { id: "TA0011", name: "Command and Control", techniques: ["T1071", "T1090", "T1573", "T1105"] },
    { id: "TA0010", name: "Exfiltration", techniques: ["T1041", "T1048", "T1567"] },
    { id: "TA0040", name: "Impact", techniques: ["T1486", "T1490", "T1489", "T1498"] },
  ],
};
